[platformio]
default_envs = stm32f103c6

[common]
build_flags =
  -std=c11
  -Wall
  -Wextra
  -Wshadow
  -Wno-unused-parameter

[env]
platform = ststm32@19.5.0
framework = stm32cube
upload_protocol = cmsis-dap
build_flags = ${common.build_flags}

[env:stm32f103c6]
board = genericSTM32F103C6

[env:stm32f103c8]
board = genericSTM32F103C8

[env:stm32f103c6_motor_check]
board = genericSTM32F103C6
build_flags =
  ${common.build_flags}
  -DAPP_ENABLE_MOTOR=1
